# Generated by Django 4.1.1 on 2022-10-28 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave',
            old_name='user',
            new_name='student',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='subject',
            field=models.CharField(choices=[('BIOLOGY', 'BIOLOGY'), ('MATHS', 'MATHS'), ('LANGUAGE', 'LANGUAGE'), ('PHYSICS', 'PHYSICS'), ('ENGLISH', 'ENGLISH'), ('CHEMISTRY', 'CHEMISTRY')], max_length=50),
        ),
        migrations.AlterField(
            model_name='teacherlogin',
            name='gender',
            field=models.CharField(choices=[('F', 'FEMALE'), ('O', 'OTHER'), ('M', 'MALE')], max_length=30),
        ),
        migrations.AlterField(
            model_name='teacherlogin',
            name='subject',
            field=models.CharField(choices=[('BIOLOGY', 'BIOLOGY'), ('MATHS', 'MATHS'), ('LANGUAGE', 'LANGUAGE'), ('PHYSICS', 'PHYSICS'), ('ENGLISH', 'ENGLISH'), ('CHEMISTRY', 'CHEMISTRY')], max_length=50),
        ),
    ]
