# Generated by Django 4.1.1 on 2022-10-28 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0002_rename_user_leave_student_alter_assignment_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='subject',
            field=models.CharField(choices=[('CHEMISTRY', 'CHEMISTRY'), ('BIOLOGY', 'BIOLOGY'), ('MATHS', 'MATHS'), ('LANGUAGE', 'LANGUAGE'), ('ENGLISH', 'ENGLISH'), ('PHYSICS', 'PHYSICS')], max_length=50),
        ),
        migrations.AlterField(
            model_name='leave',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='demoapp.studentadd'),
        ),
        migrations.AlterField(
            model_name='teacherlogin',
            name='gender',
            field=models.CharField(choices=[('F', 'FEMALE'), ('M', 'MALE'), ('O', 'OTHER')], max_length=30),
        ),
        migrations.AlterField(
            model_name='teacherlogin',
            name='subject',
            field=models.CharField(choices=[('CHEMISTRY', 'CHEMISTRY'), ('BIOLOGY', 'BIOLOGY'), ('MATHS', 'MATHS'), ('LANGUAGE', 'LANGUAGE'), ('ENGLISH', 'ENGLISH'), ('PHYSICS', 'PHYSICS')], max_length=50),
        ),
    ]
