# Generated by Django 4.1.1 on 2022-10-28 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0003_alter_assignment_subject_alter_leave_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='subject',
            field=models.CharField(choices=[('ENGLISH', 'ENGLISH'), ('CHEMISTRY', 'CHEMISTRY'), ('BIOLOGY', 'BIOLOGY'), ('LANGUAGE', 'LANGUAGE'), ('PHYSICS', 'PHYSICS'), ('MATHS', 'MATHS')], max_length=50),
        ),
        migrations.AlterField(
            model_name='teacherlogin',
            name='subject',
            field=models.CharField(choices=[('ENGLISH', 'ENGLISH'), ('CHEMISTRY', 'CHEMISTRY'), ('BIOLOGY', 'BIOLOGY'), ('LANGUAGE', 'LANGUAGE'), ('PHYSICS', 'PHYSICS'), ('MATHS', 'MATHS')], max_length=50),
        ),
    ]
