# Generated by Django 4.1.1 on 2022-11-02 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0004_leave_status_alter_assignment_subject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=200)),
                ('ans', models.CharField(max_length=100)),
                ('option1', models.CharField(max_length=100)),
                ('option2', models.CharField(max_length=100)),
                ('option3', models.CharField(max_length=100)),
                ('option4', models.CharField(max_length=100)),
                ('checkans', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='assignment',
            name='subject',
            field=models.CharField(choices=[('CHEMISTRY', 'CHEMISTRY'), ('LANGUAGE', 'LANGUAGE'), ('MATHS', 'MATHS'), ('BIOLOGY', 'BIOLOGY'), ('PHYSICS', 'PHYSICS'), ('ENGLISH', 'ENGLISH')], max_length=50),
        ),
        migrations.AlterField(
            model_name='teacherlogin',
            name='gender',
            field=models.CharField(choices=[('F', 'FEMALE'), ('O', 'OTHER'), ('M', 'MALE')], max_length=30),
        ),
        migrations.AlterField(
            model_name='teacherlogin',
            name='subject',
            field=models.CharField(choices=[('CHEMISTRY', 'CHEMISTRY'), ('LANGUAGE', 'LANGUAGE'), ('MATHS', 'MATHS'), ('BIOLOGY', 'BIOLOGY'), ('PHYSICS', 'PHYSICS'), ('ENGLISH', 'ENGLISH')], max_length=50),
        ),
    ]
